#####切片资源
####
###type
cms
###分类
切片资源
###标题
360资源
###图片
http://egwang186.top:39000/tupian.php?text=360资源
###BaseURL
"https://360zy.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
互利资源
###图片
http://egwang186.top:39000/tupian.php?text=互利资源
###BaseURL
"https://www.hulizyw.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
1080P资源
###图片
http://egwang186.top:39000/tupian.php?text=1080P资源
###BaseURL
"https://1080api.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
淘片资源
###图片
http://egwang186.top:39000/tupian.php?text=淘片资源
###BaseURL
"https://taopianapi.com/cjapi/mc10/vod/json.html";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
49资源
###图片
http://egwang186.top:39000/tupian.php?text=49资源
###BaseURL
"https://49zyw.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
华为吧
###图片
http://egwang186.top:39000/tupian.php?text=华为吧
###BaseURL
"https://hw8.live/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
索尼资源
###图片
http://egwang186.top:39000/tupian.php?text=索尼资源
###BaseURL
"https://suoniapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
豪华资源
###图片
http://egwang186.top:39000/tupian.php?text=豪华资源
###BaseURL
"https://hhzyapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
速博资源
###图片
http://egwang186.top:39000/tupian.php?text=速博资源
###BaseURL
"https://subocaiji.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
虎牙资源
###图片
http://egwang186.top:39000/tupian.php?text=虎牙资源
###BaseURL
"https://www.huyaapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
奇虎资源
###图片
http://egwang186.top:39000/tupian.php?text=奇虎资源
###BaseURL
"https://caiji.qhzyapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
魔都资源
###图片
http://egwang186.top:39000/tupian.php?text=魔都资源
###BaseURL
"https://www.moduzy.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
看看资源
###图片
http://egwang186.top:39000/tupian.php?text=看看资源
###BaseURL
"https://zy.hikan.xyz/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
最大资源
###图片
http://egwang186.top:39000/tupian.php?text=最大资源
###BaseURL
"https://api.zuidapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
暴风资源
###图片
http://egwang186.top:39000/tupian.php?text=暴风资源
###BaseURL
"https://bfzyapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
快看资源
###图片
http://egwang186.top:39000/tupian.php?text=快看资源
###BaseURL
"https://kuaikan-api.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
快云资源
###图片
http://egwang186.top:39000/tupian.php?text=快云资源
###BaseURL
"https://www.kuaiyunzy.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
CK资源
###图片
http://egwang186.top:39000/tupian.php?text=CK资源
###BaseURL
"https://ckzy.me/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
极速资源
###图片
http://egwang186.top:39000/tupian.php?text=极速资源
###BaseURL
"https://jszyapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
火狐资源
###图片
http://egwang186.top:39000/tupian.php?text=火狐资源
###BaseURL
"https://hhzyapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
步步高资源
###图片
http://egwang186.top:39000/tupian.php?text=步步高资源
###BaseURL
"https://api.yparse.com/api/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
金鹰资源
###图片
http://egwang186.top:39000/tupian.php?text=金鹰资源
###BaseURL
"https://jyzyapi.com/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
爱坤资源
###图片
http://egwang186.top:39000/tupian.php?text=爱坤资源
###BaseURL
"https://ikunzyapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
42资源
###图片
http://egwang186.top:39000/tupian.php?text=42资源
###BaseURL
"https://www.42.la/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
非凡资源
###图片
http://egwang186.top:39000/tupian.php?text=非凡资源
###BaseURL
"http://cj.ffzyapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
1080资源库
###图片
http://egwang186.top:39000/tupian.php?text=1080资源库
###BaseURL
"https://api.1080zyku.com/inc/api_mac10.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
快车资源
###图片
http://egwang186.top:39000/tupian.php?text=快车资源
###BaseURL
"https://caiji.kczyapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
量子资源
###图片
http://egwang186.top:39000/tupian.php?text=量子资源
###BaseURL
"http://cj.lziapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
卧龙资源
###图片
http://egwang186.top:39000/tupian.php?text=卧龙资源
###BaseURL
"https://collect.wolongzyw.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
红牛资源
###图片
http://egwang186.top:39000/tupian.php?text=红牛资源
###BaseURL
"https://www.hongniuzy2.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
樱花资源
###图片
http://egwang186.top:39000/tupian.php?text=樱花资源
###BaseURL
"https://m3u8.apiyhzy.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
闪电资源
###图片
http://egwang186.top:39000/tupian.php?text=闪电资源
###BaseURL
"http://sdzyapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
飞速资源
###图片
http://egwang186.top:39000/tupian.php?text=飞速资源
###BaseURL
"https://www.feisuzy.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
光速资源
###图片
http://egwang186.top:39000/tupian.php?text=光速资源
###BaseURL
"https://api.guangsuapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
新浪资源
###图片
http://egwang186.top:39000/tupian.php?text=新浪资源
###BaseURL
"http://api.xinlangapi.com/xinlangapi.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
八戒资源
###图片
http://egwang186.top:39000/tupian.php?text=八戒资源
###BaseURL
"http://cj.bajiecaiji.com/inc/apijson_vod.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
百度资源
###图片
http://egwang186.top:39000/tupian.php?text=百度资源
###BaseURL
"https://api.apibdzy.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
无尽资源
###图片
http://egwang186.top:39000/tupian.php?text=无尽资源
###BaseURL
"https://api.wujinapi.net/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
切片资源
###标题
天空资源
###图片
http://egwang186.top:39000/tupian.php?text=天空资源
###BaseURL
"https://api.tiankongapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
#####
